name: Terraform

on:
  pull_request:
    branches: [ main ]                      # run when PR targets main
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  terraform:
    if: github.event.pull_request.base.ref == 'main'   # extra guard (optional)
    name: Terraform
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Explicitly log in to Azure using the provided secrets.
      # This step ensures a fresh authentication is performed for the job.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {"clientId":"${{ secrets.AZURE_AD_CLIENT_ID_2 }}",
            "clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}",
            "tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}",
            "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan
        run: |
          terraform init -input=false
          terraform plan -out=tfplan.binary -input=false
          terraform show -json tfplan.binary > terraform-plan.json

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run OPA Policy Checks
        run: conftest test terraform-plan.json --policy policies/