name: Terraform

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  terraform:
    if: github.event.pull_request.base.ref == 'main'
    name: Terraform
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {"clientId":"${{ secrets.AZURE_AD_CLIENT_ID_2 }}",
            "clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}",
            "tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}",
            "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan (Save Binary)
        run: terraform plan -out=tfplan.binary -input=false

      - name: Convert Plan to JSON
        run: terraform show -json tfplan.binary > terraform-plan.json

      - name: Sanity Check Plan File
        run: |
          test -s terraform-plan.json || { echo "❌ ERROR: terraform-plan.json is missing or empty!"; exit 1; }

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run OPA Policy Checks
        run: conftest test terraform-plan.json --policy policies/ --namespace terraform.analysis
